#EUREKA-SERVICE REGISTRY
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
      
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1071763098670-jpom8tv6etobg9jinb125n8hikh835sp.apps.googleusercontent.com
            client-secret: "{cipher}0bc1d760459b9c0dbc6775c7d00b5e61e10ca49cb5a8fa0a874eb70b46a68a258e58685202f07a241c78acfe3e972eeeee2e65df81d2ed6d79dd1402d54d63aa"
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            provider: google
          github:
            client-id: Ov23li2gI7xs9ybI2oOt
            client-secret: "{cipher}5cdbfddff662d48df91124d3125f95eb261f4eb2ada7f138e2d666f17d395b8d93b5bf1ac3b5f17385ed0a33b467a70840084eb7f8543357752bb28b4a77f982"
            scope: read:user
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          github:
            token-uri: https://github.com/login/oauth/access_token
            authorization-uri: https://github.com/login/oauth/authorize
            user-info-uri: https://api.github.com/user
